syntax on
set nocompatible
set background=dark
colorscheme Tomorrow-Night-Bright
syntax on
set showmode
set showmatch
set ruler
set showcmd
set hlsearch
set ruler
"set directory=~/swp
nmap <CR> i<CR>
